spring:
  application:
    name: microservicio-cuenta
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bancodb}
    username: ${SPRING_DATASOURCE_USERNAME:banco}
    password: ${SPRING_DATASOURCE_PASSWORD:banco123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8082

logging:
  level:
    com.banco.cuenta: INFO
    org.springframework.web: INFO